name: Build latest commit

on:
  push:
    tags:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make Gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload build artifacts
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/libs/*.jar

      - name: GET all workspace
        id: get-commit-message
        run: |
          echo "commit-message=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/beanbag44/Nuker/commits?per_page=1" | jq '.[].commit.message')" >> "$GITHUB_OUTPUT"

      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          embed-author: "Epic Nuker"
          username: "Epic Nuker"
          content: ${{${{ steps.get-commit-message.outputs.commit-message }}}}
          avatar-url: "https://cdn.discordapp.com/icons/1277071858176495666/e390183f465176a86ad95373373cbf8b.png"
          filename: "build/libs/Nuker-${{github.ref_name}}.jar"
          webhook-url: ${{ secrets.WEBHOOK_URL }}
